# Generated by Django 3.1 on 2021-02-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.CharField(help_text='用户ID', max_length=20, primary_key=True, serialize=False, verbose_name='用户id')),
                ('nickName', models.CharField(help_text='昵称', max_length=30, verbose_name='昵称')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], default='female', help_text='性别', max_length=6, verbose_name='性别')),
                ('location', models.CharField(blank=True, help_text='地区', max_length=30, verbose_name='地区')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='简介')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('weibo_num', models.IntegerField(default=0, verbose_name='微博数')),
                ('following', models.IntegerField(default=0, verbose_name='关注数')),
                ('followers', models.IntegerField(blank=True, default=0, verbose_name='粉丝数')),
                ('VIPlevel', models.CharField(blank=True, max_length=30, verbose_name='会员等级')),
                ('verified_reason', models.CharField(blank=True, max_length=30, verbose_name='认证')),
                ('talent', models.CharField(blank=True, help_text='达人', max_length=30, verbose_name='达人')),
                ('education', models.CharField(blank=True, max_length=30, verbose_name='学习经历')),
                ('work', models.CharField(blank=True, max_length=30, verbose_name='工作经历')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
            },
        ),
    ]
