# Generated by Django 3.1 on 2021-02-12 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0002_auto_20210212_2143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='nickName',
            new_name='nickname',
        ),
    ]
