# Generated by Django 3.1 on 2021-02-13 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0003_auto_20210212_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='VIPlevel',
            field=models.IntegerField(blank=True, default=0, verbose_name='会员等级'),
        ),
    ]
