# Generated by Django 3.1 on 2021-02-13 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0004_auto_20210213_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='VIPlevel',
            field=models.IntegerField(default=0, verbose_name='会员等级'),
        ),
    ]
