# Generated by Django 3.1 on 2021-02-15 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0006_weiboinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weiboinfo',
            name='created_at',
        ),
    ]
